customer_shopping_behavior_analysis

In [100]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Hp\Downloads\customer_shopping_behavior.csv")

In [156]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchese_frequency_days,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-agedd,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-agedd,NaN,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,NaN,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-agedd,365.0,365.0

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchese_frequency_days  2251 non-null   float64
 19  purchase_frequency_days  3353 non-null   float64
dtypes: category(1), float64(3), int64(4), object(12)
memory usage: 583.0+ KB

In [158]:
# to get both summary statastic of numerical and category columns
df.describe(include = 'all')

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchese_frequency_days,purchase_frequency_days
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,2251.000000,3353.000000
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,NaN,6,7,4,NaN,NaN
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,NaN,PayPal,Every 3 Months,Young Adult,NaN,NaN
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,NaN,677,584,1028,NaN,NaN
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750051,NaN,NaN,NaN,25.351538,NaN,NaN,NaN,126.840515,101.390098
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.713590,NaN,NaN,NaN,14.447125,NaN,NaN,NaN,141.929218,124.140318
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,14.000000,7.000000
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,30.000000,14.000000
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,90.000000,90.000000
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,365.000000,90.000000
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,365.000000,365.000000

In [159]:
#summary statastic of numerical column using describ() only
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,purchese_frequency_days,purchase_frequency_days
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,2251.000000,3353.000000
mean,1950.500000,44.068462,59.764359,3.750051,25.351538,126.840515,101.390098
std,1125.977353,15.207589,23.685392,0.713590,14.447125,141.929218,124.140318
min,1.000000,18.000000,20.000000,2.500000,1.000000,14.000000,7.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,30.000000,14.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,90.000000,90.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,365.000000,90.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000,365.000000

In [160]:
df.isnull().sum()

customer_id                   0
age                           0
gender                        0
item_purchased                0
category                      0
purchase_amount               0
location                      0
size                          0
color                         0
season                        0
review_rating                 0
subscription_status           0
shipping_type                 0
discount_applied              0
previous_purchases            0
payment_method                0
frequency_of_purchases        0
age_group                     0
purchese_frequency_days    1649
purchase_frequency_days     547
dtype: int64

In [172]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group',
 'purchese_frequency_days',
 'purchase_frequency_days']

In [187]:
#  to find out the median reviwe rating withn each category and will replace that with the missing value
# if clothing item missing its reviwe rating it gets replace with the median reviwe rating of clothing item not a footware item
df ['review_rating'] = df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))

In [189]:
df.isnull().sum()

customer_id                   0
age                           0
gender                        0
item_purchased                0
category                      0
purchase_amount               0
location                      0
size                          0
color                         0
season                        0
review_rating                 0
subscription_status           0
shipping_type                 0
discount_applied              0
previous_purchases            0
payment_method                0
frequency_of_purchases        0
age_group                     0
purchese_frequency_days    1649
purchase_frequency_days     547
dtype: int64

In [190]:
# for evry uppercase in category names convert lower case with under score becouse of coding
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
# to renmae  Purchase Amount (USD) 
df = df.rename(columns={'purchase_amount_(usd)' : 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchese_frequency_days',
       'purchase_frequency_days'],
      dtype='object')

In [191]:
# create a column age_group
labels = ['Young Adult','Adult','Middle-agedd','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age','age_group']].head(10)

   age     age_group
0   55  Middle-agedd
1   19   Young Adult
2   50  Middle-agedd
3   21   Young Adult
4   45  Middle-agedd
5   46  Middle-agedd
6   63        Senior
7   27   Young Adult
8   26   Young Adult
9   57  Middle-agedd

In [225]:
df[['discount_applied','payment_method']].head(10)

  discount_applied payment_method
0              Yes          Venmo
1              Yes           Cash
2              Yes    Credit Card
3              Yes         PayPal
4              Yes         PayPal
5              Yes          Venmo
6              Yes           Cash
7              Yes    Credit Card
8              Yes          Venmo
9              Yes           Cash

In [221]:
#checking one of the column redundunt
(df['discount_applied'] == df['payment_method']).all()

np.False_

In [227]:
df = df.drop('payment_method', axis=1,errors='ignore')
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'frequency_of_purchases',
       'age_group', 'purchese_frequency_days', 'purchase_frequency_days'],
      dtype='object')